### ISSUE TITLE
Example with dynamic content

### ISSUE THREAD

**Issue by wouterds** [bogoslavskiy/rn-search-bar-animation#2]
I'll look into an example with a refresh control to load more content, reason being I've been trying to achieve the same thing for the past few days but was unable to.

**Comment by bogoslavskiy** [comment]
@wouterds 
Here is an example
https://gist.github.com/bogoslavskiy/2acb5a7ec62a3c5d969aeac3ea2d6e4b

Unfortunately, native refresh control does not work. This problem is due to padding in flatlist contentContainerStyle
It will be necessary to use custom refresh control.

**Comment by wouterds** [comment]
I know, and that's exactly the problem we've endured as well this week :(. I can't get it working :/.

**Comment by userbq201** [comment]
@wouterds use refresh control on flat list
